version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn main:create_app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker  # Убедитесь, что файл загружается здесь
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env.docker  # Загружаем .env.docker для переменных окружения базы данных
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:

networks:
  app-network: